"""Agent-core execution primitives."""

from mini_agent.agent_core.execution.agent_loop import (
    AgentSubmissionLoop,
    InMemoryLoopMessageBus,
    SubmissionEvent,
    SubmissionEventType,
    wait_for_loop_event,
    wait_for_submission_completion,
)
from mini_agent.agent_core.execution.coordinator import (
    CoordinatorRunResult,
    CoordinatorStage,
    InMemoryCoordinatorProgressBus,
    MiniCoordinator,
    StageSummary,
    WorkerResult,
    WorkerTask,
)
from mini_agent.agent_core.execution.minimal_workflow import (
    MINIMAL_WORKFLOW_STAGES,
    build_minimal_workflow_tasks,
    compose_stage_prompt,
    format_minimal_workflow_report,
    run_minimal_workflow_with_runner,
)
from mini_agent.agent_core.execution.mcp_client import ExecutionMCPClient, MCPToolDescriptor
from mini_agent.agent_core.execution.mcp_tools import (
    build_declarative_mcp_registry,
    infer_mcp_tool_attributes,
    mcp_tool_alias,
)
from mini_agent.agent_core.execution.tool_approval import ToolApprovalRequest
from mini_agent.agent_core.execution.tool_execution_coordinator import (
    AgentToolExecutionRuntime,
    AgentToolExecutionCoordinator,
    ToolExecutionBatchResult,
    ToolExecutionBatchState,
)
from mini_agent.agent_core.execution.permissions import (
    ApprovalCache,
    ApprovalEngine,
    ApprovalOutcome,
    PermissionDecision,
    PermissionPolicy,
    PermissionRule,
    invocation_fingerprint,
)
from mini_agent.agent_core.context.loop_context import AgentLoopContext, TurnContext, TurnPolicySnapshot
from mini_agent.agent_core.execution.output_masking import MaskedOutputRecord, ToolOutputMasker
from mini_agent.agent_core.execution.scheduler import SchedulerResult, SchedulerState, TurnScheduler
from mini_agent.agent_core.execution.sandbox import (
    NetworkAccessMode,
    NetworkDomainPolicy,
    SandboxBackend,
    SandboxManager,
    SandboxSelection,
    SandboxTransformResult,
    WindowsRestrictedSandbox,
    WindowsSandboxPolicy,
    extract_domains_from_command,
)
from mini_agent.agent_core.execution.tools import (
    DeclarativeTool,
    DeclarativeToolAdapter,
    DeclarativeToolAttributes,
    InterruptBehavior,
    ToolBuilder,
    ToolInvocation,
    ToolKind,
    adapt_declarative_tools,
    build_declarative_registry,
    build_runtime_adapter_path,
    infer_attributes_from_tool_name,
)

__all__ = [
    "SubmissionEventType",
    "SubmissionEvent",
    "InMemoryLoopMessageBus",
    "AgentSubmissionLoop",
    "wait_for_submission_completion",
    "wait_for_loop_event",
    "CoordinatorStage",
    "WorkerTask",
    "WorkerResult",
    "StageSummary",
    "CoordinatorRunResult",
    "InMemoryCoordinatorProgressBus",
    "MiniCoordinator",
    "MINIMAL_WORKFLOW_STAGES",
    "build_minimal_workflow_tasks",
    "compose_stage_prompt",
    "format_minimal_workflow_report",
    "run_minimal_workflow_with_runner",
    "MaskedOutputRecord",
    "ToolOutputMasker",
    "MCPToolDescriptor",
    "ExecutionMCPClient",
    "mcp_tool_alias",
    "infer_mcp_tool_attributes",
    "build_declarative_mcp_registry",
    "ToolApprovalRequest",
    "ToolExecutionBatchState",
    "ToolExecutionBatchResult",
    "AgentToolExecutionRuntime",
    "AgentToolExecutionCoordinator",
    "PermissionDecision",
    "PermissionRule",
    "PermissionPolicy",
    "ApprovalOutcome",
    "ApprovalCache",
    "ApprovalEngine",
    "invocation_fingerprint",
    "TurnPolicySnapshot",
    "TurnContext",
    "AgentLoopContext",
    "SchedulerState",
    "SchedulerResult",
    "TurnScheduler",
    "SandboxBackend",
    "SandboxSelection",
    "SandboxManager",
    "NetworkAccessMode",
    "NetworkDomainPolicy",
    "extract_domains_from_command",
    "SandboxTransformResult",
    "WindowsSandboxPolicy",
    "WindowsRestrictedSandbox",
    "ToolKind",
    "InterruptBehavior",
    "DeclarativeToolAttributes",
    "ToolInvocation",
    "DeclarativeTool",
    "ToolBuilder",
    "infer_attributes_from_tool_name",
    "build_declarative_registry",
    "DeclarativeToolAdapter",
    "adapt_declarative_tools",
    "build_runtime_adapter_path",
]
